//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Tech_News.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_muc
    {
        public int Id { get; set; }
        public Nullable<int> Id_menu { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public string Link { get; set; }
        public Nullable<int> Type_menu { get; set; }
    }
}
